name: 'Run squealer with sarif upload'
description: 'Run squealer against your PR and have the sarif report uploaded to the github repo'
author: 'Owen Rumney'

inputs:
  working_directory:
    description: |
      Directory to run the action on, from the repo root.
      Default is . ( root of the repository)
    default: '.'
  sarif_file:
    description: The path to write the sarif report, defaults to squealer.sarif
outputs:
  squealer-return-code:
    description: 'squealer command return code'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'search'
  color: 'gray-blue'